var annotated_dup =
[
    [ "gdt", "namespacegdt.html", "namespacegdt" ],
    [ "owl", "namespaceowl.html", "namespaceowl" ],
    [ "_OWL_affine3f", "struct___o_w_l__affine3f.html", "struct___o_w_l__affine3f" ],
    [ "_OWL_double2", "struct___o_w_l__double2.html", "struct___o_w_l__double2" ],
    [ "_OWL_double3", "struct___o_w_l__double3.html", "struct___o_w_l__double3" ],
    [ "_OWL_double4", "struct___o_w_l__double4.html", "struct___o_w_l__double4" ],
    [ "_OWL_float2", "struct___o_w_l__float2.html", "struct___o_w_l__float2" ],
    [ "_OWL_float3", "struct___o_w_l__float3.html", "struct___o_w_l__float3" ],
    [ "_OWL_float4", "struct___o_w_l__float4.html", "struct___o_w_l__float4" ],
    [ "_OWL_int2", "struct___o_w_l__int2.html", "struct___o_w_l__int2" ],
    [ "_OWL_int3", "struct___o_w_l__int3.html", "struct___o_w_l__int3" ],
    [ "_OWL_int4", "struct___o_w_l__int4.html", "struct___o_w_l__int4" ],
    [ "_OWL_long2", "struct___o_w_l__long2.html", "struct___o_w_l__long2" ],
    [ "_OWL_long3", "struct___o_w_l__long3.html", "struct___o_w_l__long3" ],
    [ "_OWL_long4", "struct___o_w_l__long4.html", "struct___o_w_l__long4" ],
    [ "_OWL_uint2", "struct___o_w_l__uint2.html", "struct___o_w_l__uint2" ],
    [ "_OWL_uint3", "struct___o_w_l__uint3.html", "struct___o_w_l__uint3" ],
    [ "_OWL_uint4", "struct___o_w_l__uint4.html", "struct___o_w_l__uint4" ],
    [ "_OWL_ulong2", "struct___o_w_l__ulong2.html", "struct___o_w_l__ulong2" ],
    [ "_OWL_ulong3", "struct___o_w_l__ulong3.html", "struct___o_w_l__ulong3" ],
    [ "_OWL_ulong4", "struct___o_w_l__ulong4.html", "struct___o_w_l__ulong4" ],
    [ "_OWLDeviceBuffer2D", "struct___o_w_l_device_buffer2_d.html", "struct___o_w_l_device_buffer2_d" ],
    [ "_OWLVarDecl", "struct___o_w_l_var_decl.html", "struct___o_w_l_var_decl" ]
];