var annotated_dup =
[
    [ "gdt", null, [
      [ "FixedPoint", "structgdt_1_1_fixed_point.html", "structgdt_1_1_fixed_point" ]
    ] ],
    [ "owl", null, [
      [ "common", null, [
        [ "AffineSpaceT", "structowl_1_1common_1_1_affine_space_t.html", "structowl_1_1common_1_1_affine_space_t" ],
        [ "BinaryOpResultType", "structowl_1_1common_1_1_binary_op_result_type.html", null ],
        [ "BinaryOpResultType< double, int >", "structowl_1_1common_1_1_binary_op_result_type_3_01double_00_01int_01_4.html", "structowl_1_1common_1_1_binary_op_result_type_3_01double_00_01int_01_4" ],
        [ "BinaryOpResultType< double, unsigned int >", "structowl_1_1common_1_1_binary_op_result_type_3_01double_00_01unsigned_01int_01_4.html", "structowl_1_1common_1_1_binary_op_result_type_3_01double_00_01unsigned_01int_01_4" ],
        [ "BinaryOpResultType< float, int >", "structowl_1_1common_1_1_binary_op_result_type_3_01float_00_01int_01_4.html", "structowl_1_1common_1_1_binary_op_result_type_3_01float_00_01int_01_4" ],
        [ "BinaryOpResultType< float, unsigned int >", "structowl_1_1common_1_1_binary_op_result_type_3_01float_00_01unsigned_01int_01_4.html", "structowl_1_1common_1_1_binary_op_result_type_3_01float_00_01unsigned_01int_01_4" ],
        [ "BinaryOpResultType< int, double >", "structowl_1_1common_1_1_binary_op_result_type_3_01int_00_01double_01_4.html", "structowl_1_1common_1_1_binary_op_result_type_3_01int_00_01double_01_4" ],
        [ "BinaryOpResultType< int, float >", "structowl_1_1common_1_1_binary_op_result_type_3_01int_00_01float_01_4.html", "structowl_1_1common_1_1_binary_op_result_type_3_01int_00_01float_01_4" ],
        [ "BinaryOpResultType< ScalarType, ScalarType >", "structowl_1_1common_1_1_binary_op_result_type_3_01_scalar_type_00_01_scalar_type_01_4.html", "structowl_1_1common_1_1_binary_op_result_type_3_01_scalar_type_00_01_scalar_type_01_4" ],
        [ "BinaryOpResultType< unsigned int, double >", "structowl_1_1common_1_1_binary_op_result_type_3_01unsigned_01int_00_01double_01_4.html", "structowl_1_1common_1_1_binary_op_result_type_3_01unsigned_01int_00_01double_01_4" ],
        [ "BinaryOpResultType< unsigned int, float >", "structowl_1_1common_1_1_binary_op_result_type_3_01unsigned_01int_00_01float_01_4.html", "structowl_1_1common_1_1_binary_op_result_type_3_01unsigned_01int_00_01float_01_4" ],
        [ "box_t", "structowl_1_1common_1_1box__t.html", "structowl_1_1common_1_1box__t" ],
        [ "DRand48", "structowl_1_1common_1_1_d_rand48.html", "structowl_1_1common_1_1_d_rand48" ],
        [ "interval", "structowl_1_1common_1_1interval.html", "structowl_1_1common_1_1interval" ],
        [ "LCG", "structowl_1_1common_1_1_l_c_g.html", "structowl_1_1common_1_1_l_c_g" ],
        [ "limits_traits", "structowl_1_1common_1_1limits__traits.html", null ],
        [ "limits_traits< false >", "structowl_1_1common_1_1limits__traits_3_01false_01_4.html", null ],
        [ "limits_traits< true >", "structowl_1_1common_1_1limits__traits_3_01true_01_4.html", null ],
        [ "LinearSpace2", "structowl_1_1common_1_1_linear_space2.html", "structowl_1_1common_1_1_linear_space2" ],
        [ "LinearSpace3", "structowl_1_1common_1_1_linear_space3.html", "structowl_1_1common_1_1_linear_space3" ],
        [ "long_type_of", "structowl_1_1common_1_1long__type__of.html", "structowl_1_1common_1_1long__type__of" ],
        [ "long_type_of< int32_t >", "structowl_1_1common_1_1long__type__of_3_01int32__t_01_4.html", "structowl_1_1common_1_1long__type__of_3_01int32__t_01_4" ],
        [ "long_type_of< uint32_t >", "structowl_1_1common_1_1long__type__of_3_01uint32__t_01_4.html", "structowl_1_1common_1_1long__type__of_3_01uint32__t_01_4" ],
        [ "QuaternionT", "structowl_1_1common_1_1_quaternion_t.html", "structowl_1_1common_1_1_quaternion_t" ],
        [ "vec_t", "structowl_1_1common_1_1vec__t.html", "structowl_1_1common_1_1vec__t" ],
        [ "vec_t< T, 1 >", "structowl_1_1common_1_1vec__t_3_01_t_00_011_01_4.html", "structowl_1_1common_1_1vec__t_3_01_t_00_011_01_4" ],
        [ "vec_t< T, 2 >", "structowl_1_1common_1_1vec__t_3_01_t_00_012_01_4.html", "structowl_1_1common_1_1vec__t_3_01_t_00_012_01_4" ],
        [ "vec_t< T, 3 >", "structowl_1_1common_1_1vec__t_3_01_t_00_013_01_4.html", "structowl_1_1common_1_1vec__t_3_01_t_00_013_01_4" ],
        [ "vec_t< T, 4 >", "structowl_1_1common_1_1vec__t_3_01_t_00_014_01_4.html", "structowl_1_1common_1_1vec__t_3_01_t_00_014_01_4" ]
      ] ],
      [ "device", null, [
        [ "Buffer", "structowl_1_1device_1_1_buffer.html", "structowl_1_1device_1_1_buffer" ]
      ] ],
      [ "APIContext", "structowl_1_1_a_p_i_context.html", "structowl_1_1_a_p_i_context" ],
      [ "APIHandle", "structowl_1_1_a_p_i_handle.html", "structowl_1_1_a_p_i_handle" ],
      [ "Buffer", "structowl_1_1_buffer.html", "structowl_1_1_buffer" ],
      [ "BufferPointerVariable", "structowl_1_1_buffer_pointer_variable.html", "structowl_1_1_buffer_pointer_variable" ],
      [ "BufferVariable", "structowl_1_1_buffer_variable.html", "structowl_1_1_buffer_variable" ],
      [ "Context", "structowl_1_1_context.html", "structowl_1_1_context" ],
      [ "ContextObject", "structowl_1_1_context_object.html", "structowl_1_1_context_object" ],
      [ "DeviceBuffer", "structowl_1_1_device_buffer.html", "structowl_1_1_device_buffer" ],
      [ "DeviceContext", "structowl_1_1_device_context.html", "structowl_1_1_device_context" ],
      [ "DeviceIndexVariable", "structowl_1_1_device_index_variable.html", "structowl_1_1_device_index_variable" ],
      [ "DeviceMemory", "structowl_1_1_device_memory.html", "structowl_1_1_device_memory" ],
      [ "Geom", "structowl_1_1_geom.html", "structowl_1_1_geom" ],
      [ "GeomGroup", "structowl_1_1_geom_group.html", "structowl_1_1_geom_group" ],
      [ "GeomType", "structowl_1_1_geom_type.html", "structowl_1_1_geom_type" ],
      [ "GraphicsBuffer", "structowl_1_1_graphics_buffer.html", "structowl_1_1_graphics_buffer" ],
      [ "Group", "structowl_1_1_group.html", "structowl_1_1_group" ],
      [ "GroupVariable", "structowl_1_1_group_variable.html", "structowl_1_1_group_variable" ],
      [ "HostPinnedBuffer", "structowl_1_1_host_pinned_buffer.html", "structowl_1_1_host_pinned_buffer" ],
      [ "InstanceGroup", "structowl_1_1_instance_group.html", "structowl_1_1_instance_group" ],
      [ "LaunchParams", "structowl_1_1_launch_params.html", "structowl_1_1_launch_params" ],
      [ "LaunchParamsType", "structowl_1_1_launch_params_type.html", "structowl_1_1_launch_params_type" ],
      [ "ManagedMemoryBuffer", "structowl_1_1_managed_memory_buffer.html", "structowl_1_1_managed_memory_buffer" ],
      [ "MissProg", "structowl_1_1_miss_prog.html", "structowl_1_1_miss_prog" ],
      [ "MissProgType", "structowl_1_1_miss_prog_type.html", "structowl_1_1_miss_prog_type" ],
      [ "Module", "structowl_1_1_module.html", "structowl_1_1_module" ],
      [ "Object", "structowl_1_1_object.html", "structowl_1_1_object" ],
      [ "ObjectRegistry", "structowl_1_1_object_registry.html", "structowl_1_1_object_registry" ],
      [ "ObjectRegistryT", "structowl_1_1_object_registry_t.html", "structowl_1_1_object_registry_t" ],
      [ "ProgramDesc", "structowl_1_1_program_desc.html", "structowl_1_1_program_desc" ],
      [ "RangeAllocator", "structowl_1_1_range_allocator.html", "structowl_1_1_range_allocator" ],
      [ "RayGen", "structowl_1_1_ray_gen.html", "structowl_1_1_ray_gen" ],
      [ "RayGenType", "structowl_1_1_ray_gen_type.html", "structowl_1_1_ray_gen_type" ],
      [ "RayT", "structowl_1_1_ray_t.html", "structowl_1_1_ray_t" ],
      [ "RegisteredObject", "structowl_1_1_registered_object.html", "structowl_1_1_registered_object" ],
      [ "SBT", "structowl_1_1_s_b_t.html", "structowl_1_1_s_b_t" ],
      [ "SBTObject", "structowl_1_1_s_b_t_object.html", "structowl_1_1_s_b_t_object" ],
      [ "SBTObjectBase", "structowl_1_1_s_b_t_object_base.html", "structowl_1_1_s_b_t_object_base" ],
      [ "SBTObjectType", "structowl_1_1_s_b_t_object_type.html", "structowl_1_1_s_b_t_object_type" ],
      [ "SetActiveGPU", "structowl_1_1_set_active_g_p_u.html", "structowl_1_1_set_active_g_p_u" ],
      [ "Texture", "structowl_1_1_texture.html", "structowl_1_1_texture" ],
      [ "TextureVariable", "structowl_1_1_texture_variable.html", "structowl_1_1_texture_variable" ],
      [ "TrianglesGeom", "structowl_1_1_triangles_geom.html", "structowl_1_1_triangles_geom" ],
      [ "TrianglesGeomGroup", "structowl_1_1_triangles_geom_group.html", "structowl_1_1_triangles_geom_group" ],
      [ "TrianglesGeomType", "structowl_1_1_triangles_geom_type.html", "structowl_1_1_triangles_geom_type" ],
      [ "UserGeom", "structowl_1_1_user_geom.html", "structowl_1_1_user_geom" ],
      [ "UserGeomGroup", "structowl_1_1_user_geom_group.html", "structowl_1_1_user_geom_group" ],
      [ "UserGeomType", "structowl_1_1_user_geom_type.html", "structowl_1_1_user_geom_type" ],
      [ "UserTypeVariable", "structowl_1_1_user_type_variable.html", "structowl_1_1_user_type_variable" ],
      [ "Variable", "structowl_1_1_variable.html", "structowl_1_1_variable" ],
      [ "VariableT", "structowl_1_1_variable_t.html", "structowl_1_1_variable_t" ]
    ] ],
    [ "_OWL_affine3f", "struct___o_w_l__affine3f.html", "struct___o_w_l__affine3f" ],
    [ "_OWL_double2", "struct___o_w_l__double2.html", "struct___o_w_l__double2" ],
    [ "_OWL_double3", "struct___o_w_l__double3.html", "struct___o_w_l__double3" ],
    [ "_OWL_double4", "struct___o_w_l__double4.html", "struct___o_w_l__double4" ],
    [ "_OWL_float2", "struct___o_w_l__float2.html", "struct___o_w_l__float2" ],
    [ "_OWL_float3", "struct___o_w_l__float3.html", "struct___o_w_l__float3" ],
    [ "_OWL_float4", "struct___o_w_l__float4.html", "struct___o_w_l__float4" ],
    [ "_OWL_int2", "struct___o_w_l__int2.html", "struct___o_w_l__int2" ],
    [ "_OWL_int3", "struct___o_w_l__int3.html", "struct___o_w_l__int3" ],
    [ "_OWL_int4", "struct___o_w_l__int4.html", "struct___o_w_l__int4" ],
    [ "_OWL_long2", "struct___o_w_l__long2.html", "struct___o_w_l__long2" ],
    [ "_OWL_long3", "struct___o_w_l__long3.html", "struct___o_w_l__long3" ],
    [ "_OWL_long4", "struct___o_w_l__long4.html", "struct___o_w_l__long4" ],
    [ "_OWL_uint2", "struct___o_w_l__uint2.html", "struct___o_w_l__uint2" ],
    [ "_OWL_uint3", "struct___o_w_l__uint3.html", "struct___o_w_l__uint3" ],
    [ "_OWL_uint4", "struct___o_w_l__uint4.html", "struct___o_w_l__uint4" ],
    [ "_OWL_ulong2", "struct___o_w_l__ulong2.html", "struct___o_w_l__ulong2" ],
    [ "_OWL_ulong3", "struct___o_w_l__ulong3.html", "struct___o_w_l__ulong3" ],
    [ "_OWL_ulong4", "struct___o_w_l__ulong4.html", "struct___o_w_l__ulong4" ],
    [ "_OWLDeviceBuffer2D", "struct___o_w_l_device_buffer2_d.html", "struct___o_w_l_device_buffer2_d" ],
    [ "_OWLVarDecl", "struct___o_w_l_var_decl.html", "struct___o_w_l_var_decl" ]
];